sonar.projectKey=nm01n_python-project-50
sonar.organization=nm01n

# Путь к coverage файлу
sonar.python.coverage.reportPaths=coverage.xml

# Исходники и тесты
sonar.sources=gendiff
sonar.tests=tests

# Исключения
sonar.coverage.exclusions=tests/**,**/__init__.py
sonar.test.inclusions=tests/**/*.py

# Кодировка
sonar.sourceEncoding=UTF-8
